// Code generated by MockGen. DO NOT EDIT.
// Source: token_service.go
//
// Generated by this command:
//
//	mockgen -source=token_service.go -destination=mocks/token_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/SandaruwanWeerawardhana/pos-backend/internal/entity"
	service "github.com/SandaruwanWeerawardhana/pos-backend/internal/service"
	jwt "github.com/SandaruwanWeerawardhana/pos-backend/pkg/jwt"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// DenylistAccessToken mocks base method.
func (m *MockTokenService) DenylistAccessToken(ctx context.Context, jti string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenylistAccessToken", ctx, jti, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// DenylistAccessToken indicates an expected call of DenylistAccessToken.
func (mr *MockTokenServiceMockRecorder) DenylistAccessToken(ctx, jti, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenylistAccessToken", reflect.TypeOf((*MockTokenService)(nil).DenylistAccessToken), ctx, jti, ttl)
}

// IsAccessTokenDenylisted mocks base method.
func (m *MockTokenService) IsAccessTokenDenylisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAccessTokenDenylisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAccessTokenDenylisted indicates an expected call of IsAccessTokenDenylisted.
func (mr *MockTokenServiceMockRecorder) IsAccessTokenDenylisted(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccessTokenDenylisted", reflect.TypeOf((*MockTokenService)(nil).IsAccessTokenDenylisted), ctx, jti)
}

// IssuePair mocks base method.
func (m *MockTokenService) IssuePair(ctx context.Context, userID, businessID, branchID uuid.UUID, roles []string, userAgent, ip string) (service.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePair", ctx, userID, businessID, branchID, roles, userAgent, ip)
	ret0, _ := ret[0].(service.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePair indicates an expected call of IssuePair.
func (mr *MockTokenServiceMockRecorder) IssuePair(ctx, userID, businessID, branchID, roles, userAgent, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePair", reflect.TypeOf((*MockTokenService)(nil).IssuePair), ctx, userID, businessID, branchID, roles, userAgent, ip)
}

// ParseAccessToken mocks base method.
func (m *MockTokenService) ParseAccessToken(tokenString string) (*jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", tokenString)
	ret0, _ := ret[0].(*jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockTokenServiceMockRecorder) ParseAccessToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockTokenService)(nil).ParseAccessToken), tokenString)
}

// Revoke mocks base method.
func (m *MockTokenService) Revoke(ctx context.Context, rawRefreshToken, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, rawRefreshToken, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenServiceMockRecorder) Revoke(ctx, rawRefreshToken, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenService)(nil).Revoke), ctx, rawRefreshToken, reason)
}

// RevokeAllForUser mocks base method.
func (m *MockTokenService) RevokeAllForUser(ctx context.Context, userID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockTokenServiceMockRecorder) RevokeAllForUser(ctx, userID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockTokenService)(nil).RevokeAllForUser), ctx, userID, reason)
}

// Rotate mocks base method.
func (m *MockTokenService) Rotate(ctx context.Context, verified *entity.RefreshToken, businessID, branchID uuid.UUID, roles []string, userAgent, ip string) (service.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, verified, businessID, branchID, roles, userAgent, ip)
	ret0, _ := ret[0].(service.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockTokenServiceMockRecorder) Rotate(ctx, verified, businessID, branchID, roles, userAgent, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockTokenService)(nil).Rotate), ctx, verified, businessID, branchID, roles, userAgent, ip)
}

// VerifyRefresh mocks base method.
func (m *MockTokenService) VerifyRefresh(ctx context.Context, rawRefreshToken string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefresh", ctx, rawRefreshToken)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRefresh indicates an expected call of VerifyRefresh.
func (mr *MockTokenServiceMockRecorder) VerifyRefresh(ctx, rawRefreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefresh", reflect.TypeOf((*MockTokenService)(nil).VerifyRefresh), ctx, rawRefreshToken)
}
